//Users
const ADD_USER = 'ADD_USER';
const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
const ADD_USER_ERROR = 'ADD_USER_ERROR';
const GET_USERS = 'GET_USERS';
const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
const GET_USERS_ERROR = 'GET_USERS_ERROR';
const SET_USER = 'SET_USER';
const SET_USER_SUCCESS = 'SET_USER_SUCCESS';
const SET_USER_ERROR = 'SET_USER_ERROR';
const SET_CURRENT_TAB = 'SET_CURRENT_TAB';


module.exports = {
    ADD_USER,
    ADD_USER_SUCCESS,
    ADD_USER_ERROR,
    GET_USERS,
    GET_USERS_SUCCESS,
    GET_USERS_ERROR,
    SET_USER,
    SET_USER_SUCCESS,
    SET_USER_ERROR,
    SET_CURRENT_TAB
}
